const express = require('express');
const router = express.Router();
const { supabase } = require('../config/supabase');
const emailService = require('../utils/emailService');
const { generalLimiter } = require('../middleware/rateLimiter');

// Apply rate limiting
router.use(generalLimiter);

/**
 * POST /api/demo/send-email
 * Send a demo email by fetching user data from database
 */
router.post('/demo/send-email', async (req, res) => {
  try {
    const { targetEmail, userName } = req.body;

    // Use provided email or default to your email
    const emailAddress = targetEmail || 'yash.badgujar582006@gmail.com';
    const name = userName || 'Yash';

    console.log(`🎯 Demo email requested for: ${name} (${emailAddress})`);

    // Fetch user data from database
    const { data: userData, error } = await supabase
      .from('people')
      .select('*')
      .ilike('first_name', `%${name}%`)
      .limit(5);

    let dataSource = 'manual entry';
    let dbUser = null;

    if (!error && userData && userData.length > 0) {
      dbUser = userData[0];
      dataSource = 'people table';
      console.log(`✅ Found ${userData.length} users in database`);
    } else {
      console.log('ℹ️ No database user found, using provided data');
    }

    // Create demo email template
    const emailTemplate = `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 650px; margin: 0 auto; background-color: #f8fafc;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; text-align: center; border-radius: 15px 15px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 32px; font-weight: bold;">🚀 Greetflow Demo</h1>
          <p style="color: #e0e7ff; margin: 15px 0 0 0; font-size: 18px;">Database-Driven Email Automation</p>
        </div>
        
        <div style="background: white; padding: 40px 30px; border-radius: 0 0 15px 15px; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
          <h2 style="color: #1f2937; margin-top: 0; font-size: 24px;">Hello [Recipient Name]! 👋</h2>
          
          <p style="color: #4b5563; line-height: 1.7; font-size: 17px; margin-bottom: 25px;">
            This email was automatically generated by your <strong>Greetflow email automation system</strong>. 
            The system successfully fetched data from your Supabase database and personalized this message for you.
          </p>
          
          <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); padding: 25px; border-radius: 12px; margin: 25px 0;">
            <h3 style="color: white; margin: 0 0 15px 0; font-size: 20px;">✅ Automation Status: Success!</h3>
            <div style="color: #d1fae5; font-size: 15px;">
              📡 Database Connection: Active<br>
              📧 Email Service: Operational<br>
              🎯 Personalization: Working<br>
              🔒 Security: Protected
            </div>
          </div>
          
          <div style="background: #f0f9ff; padding: 25px; border-radius: 10px; border-left: 5px solid #3b82f6; margin: 25px 0;">
            <h3 style="color: #1e40af; margin: 0 0 15px 0; font-size: 18px;">📊 Retrieved Information:</h3>
            <table style="width: 100%; color: #374151; font-size: 15px;">
              <tr><td style="padding: 5px 0; font-weight: bold;">Name:</td><td>${name}</td></tr>
              <tr><td style="padding: 5px 0; font-weight: bold;">Email:</td><td>${emailAddress}</td></tr>
              <tr><td style="padding: 5px 0; font-weight: bold;">Data Source:</td><td>${dataSource}</td></tr>
              <tr><td style="padding: 5px 0; font-weight: bold;">API Endpoint:</td><td>POST /api/demo/send-email</td></tr>
              <tr><td style="padding: 5px 0; font-weight: bold;">Timestamp:</td><td>${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</td></tr>
            </table>
          </div>
          
          <div style="text-align: center; margin: 35px 0;">
            <div style="background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%); color: white; padding: 18px 35px; border-radius: 30px; display: inline-block; font-weight: bold; font-size: 16px;">
              🎉 Email Automation Demo - Complete Success!
            </div>
          </div>
          
          <p style="color: #6b7280; font-size: 14px; margin-top: 25px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
            Dear [Recipient Name], your Greetflow system is now ready to automatically send personalized 
            birthday wishes, anniversary greetings, and event invitations to all your clients!
          </p>
        </div>
        
        <div style="text-align: center; margin-top: 20px; padding: 20px; color: #9ca3af; font-size: 13px;">
          <p style="margin: 0;">🤖 Sent via Greetflow API Demo Endpoint</p>
        </div>
      </div>
    `;

    // Send the email
    const emailResult = await emailService.sendEmail({
      to: emailAddress,
      name: name,
      subject: `🎯 Greetflow API Demo - Hello ${name}! (Database Integration Test)`,
      htmlTemplate: emailTemplate
    });

    if (emailResult.success) {
      res.json({
        success: true,
        message: 'Demo email sent successfully via API',
        data: {
          messageId: emailResult.messageId,
          recipientEmail: emailResult.recipientEmail,
          recipientName: name,
          dataSource: dataSource,
          databaseRecordsFound: userData?.length || 0,
          sentAt: new Date().toISOString()
        }
      });
    } else {
      res.status(500).json({
        success: false,
        message: 'Failed to send demo email',
        error: emailResult.message
      });
    }

  } catch (error) {
    console.error('Demo email API error:', error.message);
    res.status(500).json({
      success: false,
      message: 'Internal server error',
      error: error.message
    });
  }
});

/**
 * POST /api/demo/send-to-user
 * Send email to a specific user by fetching from users table
 */
router.post('/demo/send-to-user', async (req, res) => {
  try {
    const { userName, userEmail } = req.body;

    if (!userName && !userEmail) {
      return res.status(400).json({
        success: false,
        message: 'Either userName or userEmail is required'
      });
    }

    console.log(`🎯 Searching for user: ${userName || userEmail}`);

    // Search for user in users table
    let query = supabase.from('users').select('*');
    
    if (userName) {
      query = query.ilike('name', `%${userName}%`);
    } else if (userEmail) {
      query = query.eq('email', userEmail);
    }

    const { data: userData, error } = await query.limit(1);

    if (error) {
      throw error;
    }

    if (!userData || userData.length === 0) {
      return res.status(404).json({
        success: false,
        message: `No user found with ${userName ? 'name' : 'email'}: ${userName || userEmail}`
      });
    }

    const user = userData[0];
    console.log(`✅ Found user: ${user.name} (${user.email})`);

    // Create personalized email template
    const emailTemplate = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
          <h1 style="color: white; margin: 0; font-size: 28px;">🎉 Hello [Recipient Name]!</h1>
          <p style="color: #e0e7ff; margin: 10px 0 0 0; font-size: 16px;">Greetflow Database Email Automation</p>
        </div>
        
        <div style="background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
          <h2 style="color: #333; margin-top: 0;">Dear [Recipient Name]! 👋</h2>
          
          <p style="color: #666; line-height: 1.6; font-size: 16px;">
            This personalized email was automatically generated by fetching your information from the 
            <strong>users table</strong> in our Supabase database. The system successfully found your record and 
            created this custom message just for you!
          </p>
          
          <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6; margin: 20px 0;">
            <h3 style="color: #1e40af; margin: 0 0 10px 0;">📊 Your Information Retrieved:</h3>
            <ul style="color: #374151; margin: 0; padding-left: 20px;">
              <li><strong>Name:</strong> ${user.name}</li>
              <li><strong>Email:</strong> ${user.email}</li>
              <li><strong>Phone:</strong> ${user.phone || 'Not provided'}</li>
              <li><strong>User ID:</strong> ${user.id}</li>
              <li><strong>Source:</strong> users table</li>
            </ul>
          </div>
          
          <p style="color: #666; line-height: 1.6; font-size: 16px;">
            Hi [Recipient Name], this demonstrates that our email automation system can:
          </p>
          
          <ul style="color: #666; line-height: 1.8; font-size: 16px;">
            <li>✅ Connect to the users table in Supabase</li>
            <li>✅ Search and find your specific record</li>
            <li>✅ Extract your personal information</li>
            <li>✅ Create personalized email content</li>
            <li>✅ Replace placeholders with your actual name</li>
            <li>✅ Send emails via Gmail SMTP</li>
          </ul>
          
          <div style="text-align: center; margin: 30px 0;">
            <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 15px 30px; border-radius: 25px; display: inline-block; font-weight: bold;">
              🚀 Greetflow - Personalized for [Recipient Name]!
            </div>
          </div>
          
          <p style="color: #666; line-height: 1.6; font-size: 14px; border-top: 1px solid #e5e7eb; padding-top: 20px; margin-top: 30px;">
            <strong>Technical Details:</strong><br>
            • Database: Supabase PostgreSQL<br>
            • Table: users<br>
            • Query: Found by ${userName ? 'name' : 'email'}<br>
            • Sent via: Gmail SMTP<br>
            • Time: ${new Date().toISOString()}
          </p>
        </div>
        
        <div style="text-align: center; margin-top: 20px; color: #9ca3af; font-size: 14px;">
          <p>This email was sent automatically by Greetflow Email Automation System</p>
          <p>Personalized for ${user.name} from the users table</p>
        </div>
      </div>
    `;

    // Send the email
    const emailResult = await emailService.sendEmail({
      to: user.email,
      name: user.name,
      subject: `🎉 Hello ${user.name}! Personalized Email from Greetflow`,
      htmlTemplate: emailTemplate
    });

    if (emailResult.success) {
      res.json({
        success: true,
        message: `Email sent successfully to ${user.name}`,
        data: {
          messageId: emailResult.messageId,
          recipient: {
            name: user.name,
            email: user.email,
            id: user.id
          },
          searchedBy: userName ? 'name' : 'email',
          searchTerm: userName || userEmail,
          sentAt: new Date().toISOString()
        }
      });
    } else {
      res.status(500).json({
        success: false,
        message: 'Failed to send email',
        error: emailResult.message
      });
    }

  } catch (error) {
    console.error('Send to user API error:', error.message);
    res.status(500).json({
      success: false,
      message: 'Internal server error',
      error: error.message
    });
  }
});

/**
 * GET /api/demo/users
 * Get users from database for demo purposes
 */
router.get('/demo/users', async (req, res) => {
  try {
    const { search = 'yash', limit = 10 } = req.query;

    const { data: users, error } = await supabase
      .from('users')
      .select('id, name, email, phone, created_at')
      .ilike('name', `%${search}%`)
      .limit(parseInt(limit));

    if (error) {
      throw error;
    }

    res.json({
      success: true,
      message: `Found ${users.length} users matching '${search}'`,
      data: users,
      searchTerm: search,
      totalFound: users.length
    });

  } catch (error) {
    console.error('Demo users API error:', error.message);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch users',
      error: error.message
    });
  }
});

/**
 * POST /api/demo/template-email
 * Send emails using templates from database to specified users
 */
router.post('/demo/template-email', async (req, res) => {
  try {
    const { userNames, templateId } = req.body;

    console.log('🎯 Template-based email automation requested');

    // Step 1: Fetch template from database
    let template = null;
    if (templateId) {
      const { data: templateData, error: templateError } = await supabase
        .from('templates')
        .select('*')
        .eq('id', templateId)
        .single();

      if (templateError) {
        return res.status(404).json({
          success: false,
          message: `Template not found: ${templateError.message}`
        });
      }
      template = templateData;
    } else {
      // Get first available template
      const { data: templates, error: templateError } = await supabase
        .from('templates')
        .select('*')
        .limit(1);

      if (templateError || !templates || templates.length === 0) {
        return res.status(404).json({
          success: false,
          message: 'No templates found in database'
        });
      }
      template = templates[0];
    }

    console.log(`✅ Using template: ${template.name}`);

    // Step 2: Fetch target users
    let userQuery = supabase.from('users').select('*');
    
    if (userNames && userNames.length > 0) {
      // Search for specific users
      const nameFilters = userNames.map(name => `name.ilike.%${name}%`).join(',');
      userQuery = userQuery.or(nameFilters);
    } else {
      // Default to Rajdeep and Yash
      userQuery = userQuery.or('name.ilike.%rajdeep%,name.ilike.%yash%');
    }

    const { data: users, error: userError } = await userQuery.limit(10);

    if (userError) {
      return res.status(500).json({
        success: false,
        message: `User fetch error: ${userError.message}`
      });
    }

    if (!users || users.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'No target users found'
      });
    }

    console.log(`✅ Found ${users.length} users to email`);

    // Step 3: Send emails to all users
    const emailResults = [];
    
    for (const user of users) {
      const emailTemplate = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
            <h1 style="color: white; margin: 0; font-size: 28px;">🎉 Hello [Recipient Name]!</h1>
            <p style="color: #e0e7ff; margin: 10px 0 0 0; font-size: 16px;">Template-Based Email via API</p>
          </div>
          
          <div style="background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h2 style="color: #333; margin-top: 0;">Dear [Recipient Name]! 👋</h2>
            
            <p style="color: #666; line-height: 1.6; font-size: 16px;">
              This email was automatically generated using the <strong>"${template.name}"</strong> template 
              from your database! The system fetched both the template and your user information from 
              Supabase via API call.
            </p>
            
            <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6; margin: 20px 0;">
              <h3 style="color: #1e40af; margin: 0 0 10px 0;">📋 Template Information:</h3>
              <ul style="color: #374151; margin: 0; padding-left: 20px;">
                <li><strong>Template Name:</strong> ${template.name}</li>
                <li><strong>Template Type:</strong> ${template.type || 'Not specified'}</li>
                <li><strong>Age Group:</strong> ${template.age_group || 'Not specified'}</li>
                <li><strong>Template ID:</strong> ${template.id}</li>
              </ul>
            </div>
            
            <div style="background: #ecfdf5; padding: 20px; border-radius: 8px; border-left: 4px solid #10b981; margin: 20px 0;">
              <h3 style="color: #065f46; margin: 0 0 10px 0;">👤 Your Information:</h3>
              <ul style="color: #374151; margin: 0; padding-left: 20px;">
                <li><strong>Name:</strong> ${user.name}</li>
                <li><strong>Email:</strong> ${user.email}</li>
                <li><strong>Phone:</strong> ${user.phone || 'Not provided'}</li>
                <li><strong>User ID:</strong> ${user.id}</li>
              </ul>
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
              <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 15px 30px; border-radius: 25px; display: inline-block; font-weight: bold;">
                🚀 API-Driven Template Email for [Recipient Name]!
              </div>
            </div>
            
            <p style="color: #666; line-height: 1.6; font-size: 14px; border-top: 1px solid #e5e7eb; padding-top: 20px; margin-top: 30px;">
              <strong>API Details:</strong><br>
              • Endpoint: POST /api/demo/template-email<br>
              • Template: ${template.name}<br>
              • User: ${user.name}<br>
              • Time: ${new Date().toISOString()}
            </p>
          </div>
          
          <div style="text-align: center; margin-top: 20px; color: #9ca3af; font-size: 14px;">
            <p>This email was sent via Greetflow Template Email API</p>
          </div>
        </div>
      `;

      const emailResult = await emailService.sendEmail({
        to: user.email,
        name: user.name,
        subject: `🎉 Hello ${user.name}! Template Email from Greetflow API (${template.name})`,
        htmlTemplate: emailTemplate
      });

      emailResults.push({
        user: {
          name: user.name,
          email: user.email,
          id: user.id
        },
        template: {
          name: template.name,
          type: template.type,
          id: template.id
        },
        result: emailResult
      });
    }

    // Prepare response
    const successCount = emailResults.filter(r => r.result.success).length;
    const failCount = emailResults.filter(r => r.result.success === false).length;

    res.json({
      success: true,
      message: `Template-based emails processed: ${successCount} sent, ${failCount} failed`,
      data: {
        template: {
          name: template.name,
          type: template.type,
          id: template.id
        },
        usersFound: users.length,
        emailsSent: successCount,
        emailsFailed: failCount,
        results: emailResults.map(r => ({
          user: r.user,
          success: r.result.success,
          messageId: r.result.messageId,
          error: r.result.success ? null : r.result.message
        })),
        sentAt: new Date().toISOString()
      }
    });

  } catch (error) {
    console.error('Template email API error:', error.message);
    res.status(500).json({
      success: false,
      message: 'Internal server error',
      error: error.message
    });
  }
});

module.exports = router;
